force-app/main/default/objects/AdminItemRule__c/AdminItemRule__c.object-meta.xml
<CustomObject>
    <label>Admin Item Rule</label>
    <nameField>
        <displayFormat>AIR{000000}</displayFormat>
        <label>Admin Item Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Admin Item Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AdminItemRule__c/fields/Behavior__c.field-meta.xml
<CustomField>
    <fullName>Behavior__c</fullName>
    <label>Behavior</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>InActive</fullName>
                <default>true</default>
                <label>InActive</label>
            </value>
            <value>
                <fullName>DoNotShow</fullName>
            </value>
            <value>
                <fullName>Critical</fullName>
            </value>
            <value>
                <fullName>AlwaysShow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AdminItemRule__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <formula>NOT ( ISPICKVAL(Behavior__c,&apos;IsActive&apos;) )</formula>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AdminItemRule__c/fields/ItemLabel__c.field-meta.xml
<CustomField>
    <fullName>ItemLabel__c</fullName>
    <description>Human-readable name of the item being controlled</description>
    <inlineHelpText>Human-readable name of the item being controlled</inlineHelpText>
    <label>Item Label</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AdminItemRule__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <label>Module</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Quick Launch</fullName>
            </value>
            <value>
                <fullName>License Utilization</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AdminItemRule__c/fields/ObjectAPIName__c.field-meta.xml
<CustomField>
    <fullName>ObjectAPIName__c</fullName>
    <label>Object API Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>UserLicense</fullName>
            </value>
            <value>
                <fullName>User</fullName>
            </value>
            <value>
                <fullName>PermissionSetLicense</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AdminItemRule__c/fields/UnitCost__c.field-meta.xml
<CustomField>
    <fullName>UnitCost__c</fullName>
    <defaultValue>1</defaultValue>
    <label>UnitCost</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/AdminItemRuleService.cls
public with sharing class AdminItemRuleService {

    public static final String DO_NOT_SHOW = 'DoNotShow';
    public static final String ALWAYS_SHOW = 'AlwaysShow';
    public static final String CRITICAL = 'Critical';
    public static final String MAIN_FIELD = 'ItemLabel__c'; //all the methods in this class will return a list of values specified in this variable.
    public static final Integer MAX_ITEMS = 200;

    public static List<String> getDoNotShowItems(String objectName, String module){
        return getAdminItemRules(objectName, module, DO_NOT_SHOW);
    }
    public static List<String> getAlwaysShowItems(String objectName, String module){
        return getAdminItemRules(objectName, module, ALWAYS_SHOW);
    }
    public static List<String> getCriticalItems(String objectName, String module){
        return getAdminItemRules(objectName, module, CRITICAL);
    }
    public static List<String> getAdminItemRules(String objectName, String module, String behavior){
        List<String> lstItems = new List<String>();
        
        //escape single quotes
        objectName = String.escapeSingleQuotes(objectName);
        module = String.escapeSingleQuotes(module);
        behavior = String.escapeSingleQuotes(behavior);

        if(module == null || behavior == null){
            throw new CustomException('Null value for module or behavior. Please check your input.');
        }

        String dynamicQuery = 
        'SELECT '+ MAIN_FIELD+ ' FROM AdminItemRule__c WHERE IsActive__c=TRUE AND Module__c = :module AND Behavior__c = :behavior '; //mandatory filters ( IsActive =TRUE )

        if(objectName!=null && String.isNotBlank(objectName)){
            dynamicQuery = dynamicQuery + ' AND objectAPIName__c= :objectName ';
        }

        dynamicQuery = dynamicQuery + ' LIMIT :MAX_ITEMS '; //LIMIT is appended
        System.debug(dynamicQuery);

        for (AdminItemRule__c air : Database.query(dynamicQuery, AccessLevel.SYSTEM_MODE))
        {
            lstItems.add((String)air.get(MAIN_FIELD));
        }

        return lstItems;
    }

    public static Map<String,AdminItemRule__c> getAdminItemRules(String objectName, String module){
        Map<String,AdminItemRule__c> mapItems = new Map<String,AdminItemRule__c>();

        //escape single quotes
        objectName = String.escapeSingleQuotes(objectName);
        module = String.escapeSingleQuotes(module);

        if(module == null){
            throw new CustomException('Null value for module. Please check your input.');
        }

        for(AdminItemRule__c air : [SELECT ItemLabel__c,Behavior__c,UnitCost__c FROM AdminItemRule__c WHERE IsActive__c = TRUE AND Module__c = :module AND objectAPIName__c = :objectName LIMIT 5000 ] ){
            mapItems.put(air.ItemLabel__c,air);
        }
        return mapItems;
    }

    //Custom Exception class
    public class CustomException extends Exception {

    }
}